Repository AY2122S2-CS2103T-T11-1/tp, pull requests merged in 2022-04, with the labels that each got.

#139 Update User Guide
  docs/UserGuide.md
  docs/images/GUI.png
  docs/images/HomeScreen.png
  docs/images/LoginScreen.png
  docs/images/SignUpScreen.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Documentation

#141 Add Find command in user guide and fixed grammatical issues
  docs/UserGuide.md
  docs/index.md
Labels: priority.High, type.Documentation

#140 Fix: user guide typos and add missing information
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/CommandType.java
Labels: type.Bug, type.Documentation

#142 Bugs fixing
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/prescription/PrescriptionDate.java
Labels: type.Bug

#214 Bugs fixing
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/ViewConsultationCommand.java
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/ViewContactCommand.java
  src/main/java/seedu/address/logic/commands/medical/AddMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/ViewMedicalCommand.java
  src/main/java/seedu/address/logic/commands/prescription/AddPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/ViewPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/ViewTestResultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SummaryDisplay.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
Labels: type.Bug

#216 Add Command Manager and Fix Major Bugs
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandManager.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/ViewConsultationCommand.java
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/ViewContactCommand.java
  src/main/java/seedu/address/logic/commands/medical/AddMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/DeleteMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/ViewMedicalCommand.java
  src/main/java/seedu/address/logic/commands/prescription/AddPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/DeletePrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/ViewPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/DeleteTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/ViewTestResultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/logic/parser/prescription/DeletePrescriptionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/SummaryDisplay.java
  src/main/resources/view/prescription/PrescriptionListCard.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Enhancement, type.Bug, severity.High

#218 Remove the redundant check for NRIC and allow keyword to match with NRIC
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/model/medical/MedicalContainsKeywordsPredicate.java
Labels: type.Bug, priority.Medium, severity.Low

#219 Add link to find in ToC and add find to command summary
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#222 Fix wrong tag for test date from dt/ to td/
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#225 Fix PE-D Complaints
  docs/team/juslam19.md
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/EditConsultationCommand.java
  src/main/java/seedu/address/logic/parser/MedBookParser.java
  src/main/java/seedu/address/model/consultation/ConsultationFee.java
  src/main/java/seedu/address/model/consultation/Date.java
  src/main/java/seedu/address/model/consultation/Time.java
  src/main/java/seedu/address/model/testresult/TestDate.java
  src/main/java/seedu/address/storage/JsonAdaptedConsultation.java
Labels: priority.High, severity.High

#226 Update UG Consultation, Prescription Delete
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#233 Cosmetic bug fixes
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/EditConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/FindConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/ViewConsultationCommand.java
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/medical/AddMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/EditMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/FindMedicalCommand.java
  src/main/java/seedu/address/logic/commands/prescription/AddPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/EditPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/FindPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/EditTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/FindTestResultCommand.java
  src/main/java/seedu/address/storage/JsonAdaptedConsultation.java
Labels: priority.Medium, severity.Medium

#236 Add overloaded test method to facilitate unit testing
  src/main/java/seedu/address/model/consultation/ConsultationContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/ContactContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/medical/MedicalContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/prescription/PrescriptionContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/testresult/TestResultContainsKeywordsPredicate.java
Labels: priority.Medium

#234 Fix Duplicate bug, Message Consistency
  src/main/java/seedu/address/logic/commands/consultation/EditConsultationCommand.java
  src/main/java/seedu/address/logic/parser/consultations/EditConsultationCommandParser.java
  src/main/java/seedu/address/model/consultation/Date.java
  src/main/java/seedu/address/model/prescription/PrescriptionDate.java
  src/main/java/seedu/address/model/testresult/TestDate.java
Labels: type.Bug, priority.High

#237 Update UG
  docs/UserGuide.md
Labels: type.Documentation

#240 Add Medical Edit field requirement, Fix UG Description
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/consultation/EditConsultationCommand.java
  src/main/java/seedu/address/logic/commands/medical/EditMedicalCommand.java
  src/main/java/seedu/address/logic/commands/prescription/EditPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/EditTestResultCommand.java
  src/main/java/seedu/address/logic/parser/medical/EditMedicalCommandParser.java
Labels: type.Bug, priority.High

#239 Patch PED bugs for contact and user guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/contact/EditContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/ViewContactCommand.java
  src/main/java/seedu/address/model/patient/Nric.java
  src/main/java/seedu/address/ui/SignupWindow.java
  src/main/resources/view/SignupWindow.fxml
Labels: type.Bug, severity.Low, type.Documentation

#241 Documentation: Update clement portfolio project page (PPP)
  docs/AboutUs.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  docs/team/clement0010.md
Labels: priority.Medium, type.Documentation

#244 Fix grammatical issues in User Guide
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#248 Ppp
  docs/team/cheekean5848.md
Labels: type.Task

#249 Add contact mock data for demo video
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: type.Task

#246 Update DG for summary
  docs/DeveloperGuide.md
  docs/diagrams/SummarySequenceDiagram.puml
  docs/images/SummarySequenceDiagram.png
  src/main/java/seedu/address/logic/commands/medical/AddMedicalCommand.java
  src/main/java/seedu/address/model/medical/Age.java
Labels: type.Documentation

#251 Reformat user guide style and structure
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/images/SummaryScreen.png
Labels: type.Task

#253 Document personal contributions in PPP and fix typo in Clement's PPP
  docs/team/clement0010.md
  docs/team/joey-chance.md
Labels: priority.High, type.Documentation

#250 Update PPP
  docs/team/sibinhho99-nus.md
Labels: type.Documentation

#252 Update user guide for submission
  docs/UserGuide.md
Labels: priority.Medium, type.Documentation

#260 Add test code for test result feature
  src/main/java/seedu/address/model/testresult/TestDate.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/MedBookParserTest.java
  src/test/java/seedu/address/model/MedBookTest.java
  src/test/java/seedu/address/model/testresult/MedicalTestTest.java
  src/test/java/seedu/address/model/testresult/ResultTest.java
  src/test/java/seedu/address/model/testresult/TestDateTest.java
  src/test/java/seedu/address/model/testresult/TestResultContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/testresult/TestResultTest.java
  src/test/java/seedu/address/model/testresult/UniqueTestResultListTest.java
  src/test/java/seedu/address/storage/JsonMedBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableMedBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TestResultBuilder.java
  src/test/java/seedu/address/testutil/TypicalMedicals.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
  src/test/java/seedu/address/testutil/TypicalPrescriptions.java
  src/test/java/seedu/address/testutil/TypicalTestResults.java
Labels: priority.High

#259 Update PPP, Add Sample Consultation Data, Add Consultation Tests
  docs/UserGuide.md
  docs/team/clement0010.md
  docs/team/juslam19.md
  src/main/java/seedu/address/model/consultation/Date.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/java/seedu/address/model/consultation/ConsultationDiagnosisTest.java
  src/test/java/seedu/address/model/consultation/ConsultationFeeTest.java
  src/test/java/seedu/address/model/consultation/DateTest.java
  src/test/java/seedu/address/model/consultation/TimeTest.java
  src/test/java/seedu/address/model/consultation/UniqueConsultationListTest.java
  src/test/java/seedu/address/testutil/ConsultationBuilder.java
  src/test/java/seedu/address/testutil/TypicalConsultations.java
Labels: priority.High, type.Documentation

#266 Replace WIP placeholders from earlier
  docs/team/joey-chance.md
Labels: priority.High, type.Documentation

#268 Add sample data for test result
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.Medium

#267 User guide/fixes
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#254 Update DG
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/diagrams/AddMedicalActivityDiagram.puml
  docs/diagrams/ArchitectureDiagram.puml
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/AuthenticationClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/EncryptionClassDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/NavigationSequenceDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/diagrams/style.puml
  docs/images/AddMedicalActivityDiagram.png
  docs/images/ArchitectureDiagram.png
  docs/images/ArchitectureSequenceDiagram.png
  docs/images/AuthenticationClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/EncryptionClassDiagram.png
  docs/images/FindSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/NavigationSequenceDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandManager.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/consultation/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/commands/contact/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/medical/DeleteMedicalCommand.java
  src/main/java/seedu/address/logic/commands/prescription/DeletePrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/DeleteTestResultCommand.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/JsonMedBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableMedBook.java
  src/main/java/seedu/address/storage/MedBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/JsonMedBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableMedBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
Labels: type.Task, priority.Medium, type.Documentation

#273 Fix test result to string issue in json
  src/main/java/seedu/address/model/testresult/TestDate.java
  src/main/java/seedu/address/storage/JsonAdaptedTestResult.java
Labels: type.Bug, priority.High

#272 Style fixes for submission
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ExitSequenceDiagram.puml
  docs/diagrams/LoginSequenceDiagram.puml
  docs/images/EditScreen.PNG
  docs/images/ExitSequenceDiagram.png
  docs/images/LoginSequenceDiagram.png
  docs/team/clement0010.md
Labels: type.Task

#275 Fix wording in user guide and add additional notes
  docs/UserGuide.md
  docs/images/EditScreen.png
Labels: priority.Medium, type.Documentation
