Repository AY2122S2-CS2103T-T11-1/tp, pull requests merged in 2022-03, with the labels that each got.

#8 Update user guide overview and setup guide
  docs/UserGuide.md
  docs/images/user-guide/icon.png
Labels: documentation

#7 Add first part of Section 2.0
  docs/UserGuide.md
  docs/images/user-guide/feature2_1.png
  docs/images/user-guide/feature2_2.png
Labels: documentation

#6 User Guide Section 3.0 and 4.0
  docs/UserGuide.md
  docs/images/user-guide/feature2_8_1.png
  docs/images/user-guide/feature2_8_2.png
Labels: documentation

#9 Add create, view and edit medical information to UserGuide
  docs/UserGuide.md
  docs/images/user-guide/feature2_4.png
  docs/images/user-guide/feature2_5.png
Labels: documentation

#11 Update readme
  README.md
  docs/_config.yml
  docs/images/Ui.png
Labels: documentation

#13 Create joey-chance.md
  docs/team/joey-chance.md
Labels: documentation

#14 Add Project Portfolio Page (PPP)
  docs/team/clement0010.md
Labels: documentation

#17 Integrate user guide
  docs/UserGuide.md
  docs/images/user-guide/feature2_1.png
  docs/images/user-guide/feature2_2.png
  docs/images/user-guide/feature2_4.png
  docs/images/user-guide/feature2_5.png
  docs/images/user-guide/feature2_8_1.png
  docs/images/user-guide/feature2_8_2.png
  docs/images/user-guide/icon.png
  docs/index.md
Labels: documentation

#20 Fix some inconsistencies in User's guide
  docs/UserGuide.md
Labels: documentation

#22 Add empty line between header and table for Section 4.0 Command Summary
  docs/UserGuide.md
Labels: documentation

#18 Update Developer Guide
  docs/DeveloperGuide.md
Labels: documentation

#49 Revert "Merge branch 'master' into master"
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/testresult/AddTestResultCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/testresult/MedicalTest.java
  src/main/java/seedu/address/model/testresult/Result.java
  src/main/java/seedu/address/model/testresult/TestDate.java
  src/main/java/seedu/address/model/testresult/TestResult.java
  src/main/java/seedu/address/model/testresult/TestResultWithNricPredicate.java
  src/main/java/seedu/address/model/testresult/UniqueTestResultList.java
  src/main/java/seedu/address/model/testresult/exceptions/DuplicateTestResultException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTestResult.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/testresult/TestResultCard.java
  src/main/java/seedu/address/ui/testresult/TestResultListPanel.java
  src/main/resources/view/testresult/TestResultListCard.fxml
  src/main/resources/view/testresult/TestResultListPanel.fxml
Labels: severity.High

#47 Add add medical information command
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/medical/AddMedicalCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentTokenizer.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/medical/AddMedicalCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/medical/Age.java
  src/main/java/seedu/address/model/medical/BloodType.java
  src/main/java/seedu/address/model/medical/Ethnicity.java
  src/main/java/seedu/address/model/medical/FamilyHistory.java
  src/main/java/seedu/address/model/medical/Gender.java
  src/main/java/seedu/address/model/medical/Height.java
  src/main/java/seedu/address/model/medical/Illnesses.java
  src/main/java/seedu/address/model/medical/ImmunizationHistory.java
  src/main/java/seedu/address/model/medical/Medical.java
  src/main/java/seedu/address/model/medical/MedicalWithNricPredicate.java
  src/main/java/seedu/address/model/medical/Medication.java
  src/main/java/seedu/address/model/medical/Surgeries.java
  src/main/java/seedu/address/model/medical/UniqueMedicalList.java
  src/main/java/seedu/address/model/medical/Weight.java
  src/main/java/seedu/address/model/medical/exceptions/DuplicateMedicalException.java
  src/main/java/seedu/address/model/medical/exceptions/MedicalNotFoundException.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonUserPrefsStorage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/java/seedu/address/ui/medical/MedicalCard.java
  src/main/java/seedu/address/ui/medical/MedicalListPanel.java
  src/main/resources/view/medical/MedicalListCard.fxml
  src/main/resources/view/medical/MedicalListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: priority.High

#51 feat: Add Test Result Command #31
  docs/UserGuide.md
  docs/team/cheekean5848.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/ViewTestResultCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/testresult/AddTestResultCommandParser.java
  src/main/java/seedu/address/logic/parser/testresult/ViewTestResultCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/testresult/MedicalTest.java
  src/main/java/seedu/address/model/testresult/Result.java
  src/main/java/seedu/address/model/testresult/TestDate.java
  src/main/java/seedu/address/model/testresult/TestResult.java
  src/main/java/seedu/address/model/testresult/TestResultWithNricPredicate.java
  src/main/java/seedu/address/model/testresult/UniqueTestResultList.java
  src/main/java/seedu/address/model/testresult/exceptions/DuplicateTestResultException.java
  src/main/java/seedu/address/model/testresult/exceptions/TestResultNotFoundException.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedTestResult.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/testresult/TestResultCard.java
  src/main/java/seedu/address/ui/testresult/TestResultListPanel.java
  src/main/resources/view/testresult/TestResultListCard.fxml
  src/main/resources/view/testresult/TestResultListPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
Labels: type.Story, priority.High

#54 feat: Add Test Result Command #29
  src/main/java/seedu/address/logic/commands/contact/ViewContactCommand.java
  src/main/java/seedu/address/logic/commands/testresult/ViewTestResultCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/testresult/AddTestResultCommandParser.java
  src/main/java/seedu/address/logic/parser/testresult/ViewTestResultCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/testresult/TestResult.java
  src/main/java/seedu/address/ui/testresult/TestResultCard.java
  src/main/java/seedu/address/ui/testresult/TestResultListPanel.java
  src/main/resources/view/testresult/TestResultListCard.fxml
Labels: type.Story, priority.High

#59 feat: Delete Test Result Command #30
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/DeleteTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/ViewTestResultCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/testresult/DeleteTestResultCommandParser.java
  src/main/java/seedu/address/model/testresult/TestResult.java
  src/main/java/seedu/address/model/testresult/TestResultWithNricPredicate.java
  src/main/java/seedu/address/storage/JsonAdaptedTestResult.java
Labels: type.Story, priority.High

#63 Branch delete function
  docs/tutorials/AddRemark.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/prescription/DeletePrescriptionCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/prescription/DeletePrescriptionCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/java/seedu/address/ui/PatientListPanel.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/images/MedBook.png
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/testresult/TestResultListCard.fxml
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: type.Story, priority.High

#60 Add delete medical information command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/medical/DeleteMedicalCommand.java
  src/main/java/seedu/address/logic/parser/medical/DeleteMedicalCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.High

#64 Improved Delete Command
  gradle.properties
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/ViewContactCommand.java
  src/main/java/seedu/address/logic/commands/testresult/DeleteTestResultCommand.java
  src/main/java/seedu/address/logic/parser/testresult/DeleteTestResultCommandParser.java
Labels: type.Story, type.Bug, priority.High

#58 Add, Delete, View Consultation & Changed Delete to Index System
  docs/tutorials/RemovingFields.md
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/ViewConsultationCommand.java
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/consultations/AddConsultationCommandParser.java
  src/main/java/seedu/address/logic/parser/consultations/DeleteConsultationCommandParser.java
  src/main/java/seedu/address/logic/parser/consultations/ViewConsultationCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/consultation/Consultation.java
  src/main/java/seedu/address/model/consultation/ConsultationWithPredicates.java
  src/main/java/seedu/address/model/consultation/Date.java
  src/main/java/seedu/address/model/consultation/Notes.java
  src/main/java/seedu/address/model/consultation/Prescription.java
  src/main/java/seedu/address/model/consultation/TestsTakenAndResults.java
  src/main/java/seedu/address/model/consultation/Time.java
  src/main/java/seedu/address/model/consultation/UniqueConsultationList.java
  src/main/java/seedu/address/model/consultation/exceptions/ConsultationNotFoundException.java
  src/main/java/seedu/address/model/consultation/exceptions/DuplicateConsultationException.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/UniquePersonList.java
  src/main/java/seedu/address/model/testresult/exceptions/DuplicateTestResultException.java
  src/main/java/seedu/address/storage/JsonAdaptedConsultation.java
  src/main/java/seedu/address/storage/JsonAddressBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/consultation/ConsultationCard.java
  src/main/java/seedu/address/ui/consultation/ConsultationListPanel.java
  src/main/resources/view/consultation/ConsultationListCard.fxml
  src/main/resources/view/consultation/ConsultationListPanel.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/patient/AddressTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
Labels: priority.High

#66 Add storing medical information
  src/main/java/seedu/address/storage/JsonAdaptedMedical.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
Labels: type.Enhancement

#67 Add view all medical details when NRIC not specified + fix saving bug
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/medical/ViewMedicalCommand.java
  src/main/java/seedu/address/logic/parser/medical/ViewMedicalCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/medical/UniqueMedicalList.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/medical/MedicalCard.java
  src/main/resources/view/medical/MedicalListCard.fxml
Labels: type.Enhancement, type.Bug

#79 Add documentation base structure for developer guide
  docs/DeveloperGuide.md
Labels: type.Documentation

#82 Patch user guide
  build.gradle
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/index.md
Labels: type.Documentation

#83 Update developer guide to include Add command features
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#84 Add implementation details for Find in Developer's Guide
  docs/DeveloperGuide.md
Labels: priority.High, type.Documentation

#86 Add UML and Activity Diagrams for add commands feature
  docs/DeveloperGuide.md
  docs/diagrams/AddMedicalActivityDiagram.puml
  docs/diagrams/AllAddCommandsClassDiagram.puml
  docs/images/AddMedicalActivityDiagram.png
  docs/images/AllAddCommandsClassDiagram.png
Labels: priority.High, type.Documentation

#87 Add edit medical information command
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/medical/EditMedicalCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/medical/AddMedicalCommandParser.java
  src/main/java/seedu/address/logic/parser/medical/EditMedicalCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.High

#89 feat: Edit Test Result Command #88
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/medical/EditMedicalCommand.java
  src/main/java/seedu/address/logic/commands/testresult/DeleteTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/EditTestResultCommand.java
  src/main/java/seedu/address/logic/parser/testresult/EditTestResultCommandParser.java
Labels: type.Story, priority.High

#90 Update DG View
  docs/DeveloperGuide.md
  docs/images/ViewSequenceDiagram.png
Labels: priority.High

#92 Add command history to MedBook
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/history/CommandHistory.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/resources/view/CommandBox.fxml
Labels: type.Story, priority.Medium

#94 Ensure medical information in user's guide matches current version + Fix cosmetics issues in UG
  README.md
  docs/UserGuide.md
  docs/_config.yml
  src/main/java/seedu/address/logic/parser/medical/AddMedicalCommandParser.java
  src/main/java/seedu/address/model/medical/Age.java
  src/main/java/seedu/address/model/medical/BloodType.java
Labels: type.Enhancement, type.Documentation

#95 Improve User's Guide
  docs/UserGuide.md
  docs/index.md
  docs/team/sibinhho99-nus.md
Labels: type.Documentation

#97 Add Consultation Edit Feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/consultation/EditConsultationCommand.java
  src/main/java/seedu/address/logic/parser/consultations/EditConsultationCommandParser.java
  src/main/java/seedu/address/ui/consultation/ConsultationCard.java
  src/main/resources/view/consultation/ConsultationListCard.fxml
Labels: type.Story, priority.High

#99 Add edit prescription function
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/prescription/EditPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/EditTestResultCommand.java
  src/main/java/seedu/address/logic/parser/prescription/EditPrescriptionCommandParser.java
Labels: priority.Medium

#106 feat: Find Test Result Command
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/ViewedNric.java
  src/main/java/seedu/address/logic/commands/testresult/FindTestResultCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/consultations/AddConsultationCommandParser.java
  src/main/java/seedu/address/logic/parser/consultations/ViewConsultationCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/AddContactCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/ViewContactCommandParser.java
  src/main/java/seedu/address/logic/parser/medical/AddMedicalCommandParser.java
  src/main/java/seedu/address/logic/parser/medical/ViewMedicalCommandParser.java
  src/main/java/seedu/address/logic/parser/prescription/AddPrescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/prescription/ViewPrescriptionCommandParser.java
  src/main/java/seedu/address/logic/parser/testresult/AddTestResultCommandParser.java
  src/main/java/seedu/address/logic/parser/testresult/FindTestResultCommandParser.java
  src/main/java/seedu/address/logic/parser/testresult/ViewTestResultCommandParser.java
  src/main/java/seedu/address/model/testresult/TestResultContainsKeywordsPredicate.java
Labels: type.Enhancement, priority.Medium

#110 feat: Add encryption and authentication feature
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/authentication/Authentication.java
  src/main/java/seedu/address/authentication/AuthenticationException.java
  src/main/java/seedu/address/authentication/AuthenticationManager.java
  src/main/java/seedu/address/commons/util/AesUtil.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/encryption/Encryption.java
  src/main/java/seedu/address/encryption/EncryptionManager.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/SignupWindow.java
  src/main/resources/images/approve.png
  src/main/resources/images/reject.png
  src/main/resources/view/LightTheme.css
  src/main/resources/view/LoginWindow.fxml
  src/main/resources/view/SignupWindow.fxml
  src/test/java/seedu/address/encryption/EncryptionManagerTest.java
Labels: type.Story, priority.High

#107 Add view summary feature
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/CollectionUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ViewCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/SummaryDisplay.java
  src/main/resources/images/MedBook.png
  src/main/resources/images/MedBook_32.png
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/LightTheme.css
  src/main/resources/view/SummaryDisplay.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
Labels: type.Enhancement, type.Documentation

#113 feat: Find Command #100
  src/main/java/seedu/address/logic/commands/CommandType.java
  src/main/java/seedu/address/logic/commands/consultation/FindConsultationCommand.java
  src/main/java/seedu/address/logic/commands/contact/FindContactCommand.java
  src/main/java/seedu/address/logic/commands/medical/FindMedicalCommand.java
  src/main/java/seedu/address/logic/commands/prescription/FindPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/FindTestResultCommand.java
  src/main/java/seedu/address/logic/parser/consultations/FindConsultationCommandParser.java
  src/main/java/seedu/address/logic/parser/contact/FindContactCommandParser.java
  src/main/java/seedu/address/logic/parser/medical/FindMedicalCommandParser.java
  src/main/java/seedu/address/logic/parser/prescription/FindPrescriptionCommandParser.java
  src/main/java/seedu/address/model/consultation/ConsultationContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/contact/ContactContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/medical/MedicalContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/prescription/PrescriptionContainsKeywordsPredicate.java
Labels: type.Enhancement, priority.Medium

#116 Fix UI Looks, Add Functionality
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/EditConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/ViewConsultationCommand.java
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/ViewContactCommand.java
  src/main/java/seedu/address/logic/commands/medical/AddMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/DeleteMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/EditMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/ViewMedicalCommand.java
  src/main/java/seedu/address/logic/commands/prescription/AddPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/DeletePrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/ViewPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/DeleteTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/EditTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/ViewTestResultCommand.java
  src/main/java/seedu/address/model/consultation/Consultation.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/consultation/ConsultationListPanel.java
  src/main/resources/view/LightTheme.css
  src/main/resources/view/LoginWindow.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement, priority.Medium

#112 Branch safe delete
  LICENSE
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ViewCommand.java
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/commands/consultation/ViewConsultationCommand.java
  src/main/java/seedu/address/logic/commands/contact/AddContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/DeleteContactCommand.java
  src/main/java/seedu/address/logic/commands/contact/ViewContactCommand.java
  src/main/java/seedu/address/logic/commands/medical/AddMedicalCommand.java
  src/main/java/seedu/address/logic/commands/medical/ViewMedicalCommand.java
  src/main/java/seedu/address/logic/commands/prescription/AddPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/DeletePrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/prescription/ViewPrescriptionCommand.java
  src/main/java/seedu/address/logic/commands/testresult/AddTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/DeleteTestResultCommand.java
  src/main/java/seedu/address/logic/commands/testresult/ViewTestResultCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/ui/LoginWindow.java
  src/main/java/seedu/address/ui/SignupWindow.java
  src/main/java/seedu/address/ui/prescription/PrescriptionListPanel.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ViewCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/patient/NameContainsKeywordsPredicateTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/model/patient/UniquePatientListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/JsonAddressBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/AddressBookBuilder.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.Medium

#125 Fix delete last entry bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/consultation/DeleteConsultationCommand.java
  src/main/java/seedu/address/logic/commands/medical/DeleteMedicalCommand.java
Labels: type.Bug

#126 Fix: Password UI Bug
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/SignupWindow.java
  src/main/resources/view/SignupWindow.fxml
Labels: type.Bug, priority.Medium

#128 Fix: Allow editable file to meet project constraint
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/encryption/EncryptionManager.java
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Bug, severity.Low

#129 Release/v1.3.1
  build.gradle
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/model/UserPrefs.java
Labels: type.Task

#131 Allow blood type to take any values
  src/main/java/seedu/address/model/medical/BloodType.java
Labels: type.Bug, severity.VeryLow

#130 Add Consultation Edit in UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/consultation/AddConsultationCommand.java
  src/main/java/seedu/address/logic/parser/consultations/AddConsultationCommandParser.java
  src/main/java/seedu/address/model/consultation/ConsultationNotes.java
  src/main/java/seedu/address/storage/JsonAdaptedConsultation.java
  src/main/java/seedu/address/ui/consultation/ConsultationCard.java
  src/main/resources/view/LightTheme.css
Labels: priority.High

#132 Update tag command format in UG
  docs/UserGuide.md
Labels: type.Documentation
